extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
  subject-case:
    - 2
    - never
    - - upper-case
      - pascal-case
      - start-case
  subject-empty:
    - 2
    - never
  type-empty:
    - 2
    - never
  scope-case:
    - 2
    - always
    - lower-case
