from __future__ import annotations

from descope._http_base import HTTPBase
from descope.management._engine_base import EngineBase
from descope.management.common import MgmtV1


class Engine(EngineBase, HTTPBase):
    def create(self, name: str) -> dict:
        """
        Create a new engine with the given name. The engine ID and secret are
        generated by Descope and returned in the response.

        Args:
        name (str): The engine's name.

        Return value (dict):
        Return dict in the format
             {"engine": {"id": <id>, "name": <name>, "secret": <secret>, ...}}
        The secret is returned ONLY on create and rotate_secret; store it securely.

        Raise:
        AuthException: raised if create operation fails
        """
        response = self._http.post(
            MgmtV1.engine_create_path,
            body=EngineBase._compose_create_body(name),
        )
        return response.json()

    def update(self, id: str, name: str) -> dict:
        """
        Update an existing engine's name.

        Args:
        id (str): The ID of the engine to update.
        name (str): Updated engine name.

        Return value (dict):
        Return dict in the format {"engine": {...}} (without the secret).

        Raise:
        AuthException: raised if update operation fails
        """
        response = self._http.post(
            MgmtV1.engine_update_path,
            body=EngineBase._compose_update_body(id, name),
        )
        return response.json()

    def delete(self, id: str):
        """
        Delete an existing engine. IMPORTANT: This action is irreversible. Use carefully.

        Args:
        id (str): The ID of the engine to delete.

        Raise:
        AuthException: raised if deletion operation fails
        """
        self._http.post(MgmtV1.engine_delete_path, body={"id": id})

    def load(self, id: str) -> dict:
        """
        Load an engine by ID. The returned engine's secret is always empty.

        Args:
        id (str): The ID of the engine to load.

        Return value (dict):
        Return dict in the format {"engine": {...}}.

        Raise:
        AuthException: raised if load operation fails
        """
        response = self._http.get(MgmtV1.engine_load_path, params={"id": id})
        return response.json()

    def load_all(self) -> dict:
        """
        Load all engines for the project. The returned engines' secrets are always empty.

        Return value (dict):
        Return dict in the format {"engines": [{...}, ...]}.

        Raise:
        AuthException: raised if load operation fails
        """
        response = self._http.get(MgmtV1.engine_load_all_path)
        return response.json()

    def rotate_secret(self, id: str) -> dict:
        """
        Rotate an engine's secret, invalidating the previous one and returning the
        new secret in cleartext. Store it securely; it cannot be retrieved again.

        Args:
        id (str): The ID of the engine whose secret to rotate.

        Return value (dict):
        Return dict in the format {"secret": <new_secret>}.

        Raise:
        AuthException: raised if rotate operation fails
        """
        response = self._http.post(MgmtV1.engine_rotate_secret_path, body={"id": id})
        return response.json()
