name: Leaks checks
description: 'gitleaks checks'
runs:
  using: "composite"
  steps:
    - name: gitleaks checks
      run: |
        chmod +x ./scripts/gitleaks/gitleaks.sh
        ./scripts/gitleaks/gitleaks.sh
      shell: bash
